config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path_prefix: 'my', controllers: {
    sessions: 'profiles/sessions',
    confirmations: 'profiles/confirmations',
    passwords: 'profiles/passwords'
  }

  devise_scope :user do
    get 'my/users/edit' => 'profiles/registrations#edit', as: 'edit_user_registration'
    put 'my/users' => 'profiles/registrations#update', as: 'user_registration'
    delete 'my/users' => 'profiles/registrations#destroy'
    patch 'my/users/confirmation' => 'profiles/confirmations#update', via: :patch, as: :update_user_confirmation
  end

  resources :users do
    put :deactivate
    put :reactivate
  end

  resources :drawings, :organisations

  get 'hxlstats', to: 'hxlstats#show'

  root 'drawings#index'

  namespace :api, defaults: { format: :hal } do
    resources :drawings
  end
end

app/models/organisation.rb
class Organisation < ActiveRecord::Base
  obfuscate_id spin: ENV['OBFUSCATE_ID_SPIN_NUMBER'].to_i
  alias_attribute :dml_id, :to_param

  validates :name, presence: true

  has_many :users
end

app/controllers/organisations_controller.rb
class OrganisationsController < ApplicationController
  before_action :authenticate_user!, :authorize_super_admin!
  before_action :find_organisation, only: [:edit, :show, :update, :destroy]

  def index
    @organisations = Organisation.all.order("name ASC")
  end

  def show
  end

  def new
    @organisation = Organisation.new
  end

  def create
    @organisation = Organisation.new(organisation_params)
    if @organisation.save
      flash[:success] = "Your organisation was created."
      redirect_to organisations_path
    else
      flash.now[:error] = "Sorry, your organisation could not be saved. Please review your changes and try again."
      render :new
    end
  end

  def edit
  end

  def update
    if @organisation.update(organisation_params)
      flash[:success] = "Your organisation was updated."
      redirect_to organisations_path
    else
      flash.now[:error] = "Sorry, your organisation could not be saved. Please review your changes and try again."
      render :edit
    end
  end

  def destroy
    @organisation.destroy
    redirect_to organisations_path
  end

  private

  def organisation_params
    params.require(:organisation).permit(:name)
  end

  def find_organisation
    @organisation = Organisation.find(params[:id])
  end
end

app/views/organisations/_form.html.haml
= simple_form_for @organisation do |f|
  = f.input :name, required: true, label:false, placeholder: "Name of organisation"
  = f.button :submit, class: 'btn-success btn-block'

app/views/organisations/_organisation.html.haml
.organisation-wrapper.container
  .organisation
    .row
      %strong Name:
      = organisation.name

app/views/organisations/edit.html.haml
.container
  .row
    .col-md-10.col-md-offset-1
      %h1= @organisation.name
      = render 'form'

.text-center.edit-links
  = link_to "Back To List", organisations_path

app/views/organisations/index.html.haml
.container
  .row
    .col-md-10.col-md-offset-1
      %h1 Organisations
      = link_to "Add new organisation", new_organisation_path
      - @organisations.each do |organisation|
        %h3= organisation.name
        = link_to "Edit", edit_organisation_path(organisation), class: 'btn btn-default'
        = link_to "Delete", organisation_path(organisation), method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-danger'

app/views/organisations/new.html.haml
.container
  .row
    .col-md-10.col-md-offset-1
      %h1 New Organisation
      = render 'form'

app/views/organisations/show.html.haml
= render 'organisation', organisation: @organisation
.text-center.edit-links
  = link_to "View all organisations", organisations_path
  |
  = link_to "Edit Organisation", edit_organisation_path(@organisation)