config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path_prefix: 'my', controllers: {
    sessions: 'profiles/sessions',
    confirmations: 'profiles/confirmations',
    passwords: 'profiles/passwords'
  }

  devise_scope :user do
    get 'my/users/edit' => 'profiles/registrations#edit', as: 'edit_user_registration'
    put 'my/users' => 'profiles/registrations#update', as: 'user_registration'
    delete 'my/users' => 'profiles/registrations#destroy'
    patch 'my/users/confirmation' => 'profiles/confirmations#update', via: :patch, as: :update_user_confirmation
  end

  resources :users do
    put :deactivate
    put :reactivate
  end

  resources :drawings, :organisations

  get 'hxlstats', to: 'hxlstats#show'

  root 'drawings#index'

  namespace :api, defaults: { format: :hal } do
    resources :drawings
  end
end

app/views/layouts/_logged_out.html.haml
.login-bg
  .container
    .row
      .col-md-4.col-md-offset-4
        .log-in.panel
          .panel-heading
            %h2
              = heading
          .panel-body
            = yield
        - if links
          = render "profiles/shared/links"

app/views/layouts/_navbar.html.haml
.navbar.navbar-default.navbar-static-top
  .container
    %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    .navbar-brand= link_to "Draw My Life", root_path
    .navbar-collapse.collapse.navbar-responsive-collapse
      %ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          %li
            = link_to root_path do
              %i.fa.fa-home{"aria-hidden" => "true"}
              Manage Drawings
          %li
            = link_to new_drawing_path do
              %i.fa.fa-plus{"aria-hidden" => "true"}
              Add Drawing
          %li.dropdown
            %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
              = current_user.email
              %span.caret
            %ul.dropdown-menu
              %li
                = link_to "My Profile", edit_user_registration_path(current_user)
              - if current_user.super_admin?
                %li
                  = link_to "Users", users_path
              %li
                = link_to "Organisations", organisations_path if current_user.super_admin?
              %li
                = link_to "Logout", destroy_user_session_path, method: :delete
        - else
          %li.dropdown
            %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
              Sign in
              %span.caret
            %ul.dropdown-menu
              %li
                = link_to "Login", new_user_session_path
              %li
                = link_to "Re-Send Password", new_user_password_path
              %li
                = link_to "Re-send Activation Details", new_user_confirmation_path

    / /.navbar-collapse
  / /.container-fluid

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta(name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no")
    %title DrawMyLifeService
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  %body
    = render 'layouts/navbar'
    - flash.each do |name, msg|
      .container
        = content_tag :div, msg, class: [:alert, alert_for(name)]
    = yield
    - if Rails.env.production?
      = javascript_include_tag 'hotjar.js'
      = javascript_include_tag 'google-analytics.js'